### ISSUE TITLE
Code integrity

### ISSUE THREAD

**Issue by habatua** [tridivb/slowfast_feature_extractor#8]
When I run the program separately, there were some packages that didn't exist. So I put this code in my source code on SlowFast, and after I tried to modify it, the configuration file complained of an error, and I got the following error: 
AssertionError: An object named 'SlowFast' was already registered in 'MODEL' registry!
Maybe there is other method to run the program? and Could you tell me what the final feature format looks like? 
Looking forward to your reply,Thanks!

**Comment by tridivb** [comment]
Hi,

Thank you for using the framework. Could you tell me what you mean by "run the program separately"? Please let me know the steps you followed.

Regards

**Comment by habatua** [comment]
> Hi,
> 
> Thank you for using the framework. Could you tell me what you mean by "run the program separately"? Please let me know the steps you followed. Also which packages are you referring to?
> 
> Regards

I'm so sorry.I mean When I run the code independently not separately.  （Running your program alone is missing utils?) and my files are arranged in the form of source code:
|---slowfast
|   |---checkpoints
|   |---config
|   |---dataset
|   |---models
|   |---run_net
|   |---test_net
|   |---utils
|---tools
|---...

**Comment by habatua** [comment]
> Hi,
> 
> Thank you for using the framework. Could you tell me what you mean by "run the program separately"? Please let me know the steps you followed. Also which packages are you referring to?
> 
> Regards

Hi,


> Hi,
> 
> Thank you for using the framework. Could you tell me what you mean by "run the program separately"? Please let me know the steps you followed. Also which packages are you referring to?
> 
> Regards
I'm sorry for the problems caused by the wrong application of the program. Thank you very much for your patient answer. But now I have a new problem. When I run a demo, I'm going to save the path to the video

/ home/data2 / wangjunying/wjydata/demo / 47 f8a252ea05776a7bf4df8d25063f5e. Mp4, my configuration file path is as follows:

PATH_TO_DATA_DIR: "/ home/data2 / wangjunying/wjydata/demo"

PATH_PREFIX: "/ home/data2 / wangjunying/wjydata/demo"

But when I ran it, the following error occurred:

Loading Video List...

The Done

----------------------------------------------------------

1 Videos to be processed...

----------------------------------------------------------

0. 47 f8a252ea05776a7bf4df8d25063f5e Processing. Mp4...

Traceback (most recent call Last):

File "run_net.py", line 132, in

The main ()

File "run_net.py", line 128, in main

The test (CFG = CFG)

The File "/ home/data2 / wangjunying/project/slowfast/test_net py", line 169, in the test

CFG, path_to_vid vid_id, read_vid_file = CFG. DATA. Read_vid_file

The File "/ home/data2 / wangjunying/project/slowfast datasets/videoset. Py", line 53, in __init__

The self. The frames = self. _get_frames ()

The File "/ home/data2 / wangjunying/project/slowfast datasets/videoset. Py", line 108, in _get_frames

OS. Listdir (path_to_frames),

NotADirectoryError: [20] Errno Not a directory: '/ home/data2 / wangjunying/wjydata/demo / 47 f8a252ea05776a7bf4df8d25063f5e. Mp4'

Is it because I didn't draw frames before? Can you help me take a look at it?

Thank you very much!

**Comment by habatua** [comment]
Hi,
I'm sorry for the problems caused by the wrong application of the program. Thank you very much for your patient answer. But now I have a new problem. When I run a demo, The path I save  the video is in / home/data2 / wangjunying/wjydata/demo / 47 f8a252ea05776a7bf4df8d25063f5e. mp4, and my configuration file path is as follows:

PATH_TO_DATA_DIR: "/ home/data2 / wangjunying/wjydata/demo"

PATH_PREFIX: "/ home/data2 / wangjunying/wjydata/demo"

But when I ran it, the following error occurred:
Loading Video List...
The Done
----------------------------------------------------------
1 Videos to be processed...
----------------------------------------------------------
0. 47 f8a252ea05776a7bf4df8d25063f5e Processing. Mp4...
Traceback (most recent call Last):
File "run_net.py", line 132, in
The main ()
File "run_net.py", line 128, in main
The test (CFG = CFG)
The File "/ home/data2 / wangjunying/project/slowfast/test_net py", line 169, in the test
CFG, path_to_vid vid_id, read_vid_file = CFG. DATA. Read_vid_file
The File "/ home/data2 / wangjunying/project/slowfast datasets/videoset. Py", line 53, in __init__
The self. The frames = self. _get_frames ()
The File "/ home/data2 / wangjunying/project/slowfast datasets/videoset. Py", line 108, in _get_frames
OS. Listdir (path_to_frames),
NotADirectoryError: [20] Errno Not a directory: '/ home/data2 / wangjunying/wjydata/demo / 47 f8a252ea05776a7bf4df8d25063f5e. Mp4'
Is it because I didn't draw frames before? Can you help me take a look at it?
Thank you very much!

**Comment by tridivb** [comment]
Hi,

Could you check if those paths you listed are correct? First, check if it actually exists and then verify if your path in the config is correct or not. I can see blank spaces in the path. Maybe that is causing the issue?

**Comment by habatua** [comment]
Hi，One place I don't know if I understand correctly.By reading your code,I understand each frame will extract a feature vector. And is (the number of video frames,2304).But I learned from the code of model, That seems before avgpooling layer,the fast channel is 32,and then to 1.Is the (the number of video frames,2304) leads to repeat feature,and (the number of video frames/32,2304) more reasonable? 
Regard

**Comment by tridivb** [comment]
@habatua 

If I get the question correctly, you are asking if the features are repeated. It would be better to mention the line of code that confuses you so that I can take a look at it myself. :-) 

The feature extraction is not done over each frame but over video clips. For more details on the slow and fast pathways, I suggest looking at the original paper. The final output files contain features over the entire video. As to how frequently the video clips are sampled, is dictated by the input and output fps. There might be some overlap between the sampled video clips, but since we select clips at some specific interval (output fps), all or most of them should be unique. 

Take a look at how the _getitem_ function works.

https://github.com/tridivb/slowfast_feature_extractor/blob/d52cb637721c6354fb15d537ccc133b60925f9d7/datasets/videoset.py#L162

**Comment by habatua** [comment]
start = int(index - self.step_size * self.out_size / 2)    
end = int(index + self.step_size * self.out_size / 2)
I'm sorry I can't understand what's the mean.I think (start,step,end) is the input of model(32 frames). As I know,The index is video's index（maybe which represents video clips's index?), and assuming step is 1(in_fps =15,out_fps),When index is 0,the start is -16 and the end is 16.  I don't understand  why do we take negative Numbers. And if I want to get the first frame's feature, Obviously there's no 15 frames before that.Could You explain what these two lines of code mean? 
Thank you very much!

**Comment by tridivb** [comment]
You are correct. The start, end and step together constitute the window of a video clip. To clip is initialized as a zero tensor and then the selected index is chosen as the centre of that clip. All frames with negative values are ignored and this means it is zero-padded. For index 0, it is zero-padded 15 times to the left. We do this so that one can start sampling from the first frame itself. You have to look at the whole function to understand those two lines. The for loop in line 191 is where the negative values are discarded and the video clip is created. Maybe I should improve the documentation on this part. Thank you for pointing it out.

https://github.com/tridivb/slowfast_feature_extractor/blob/d52cb637721c6354fb15d537ccc133b60925f9d7/datasets/videoset.py#L191

**Comment by habatua** [comment]
Hi,
Could you help me to see what is wrong with my understanding? As you said,The start, end and step together constitute the window of a video clip. Then every video clip is 32. If a video contains 200 frames,we input 200 clip of 32 size to the model,The we get (200,2304). According to my understanding, the input video clip is overlapped(200*32), I think I may not understand what Getitem means, which makes me very confused.
Thank you very much for your recent patience.

**Comment by tridivb** [comment]
Hi,

You are correct, if there are 200 input frames, there will be 200 features. The clips are generated by selecting a window of 32 frames while considering each input frame as the centre of the window. It does not mean that all the video clips are the same. 

Let us take an example,
Suppose you have a 4 seconds video, recorded at 60 fps. For simplicity, we will sample the video at 60 fps i.e. the input fps is 60 and also the output fps. Then features will be generated for all the frames in the video as the `step size=input fps/output fps=1`. There are now `60*4=240` frames in the video. We start at the first frame i.e. `index=0` and select a window of 32. As there are no valid frames to the left of index 0, the left part of the window is entirely zero-padded. The right side will contain valid frames as it falls within the boundary. For index 1, the second frame is selected and we repeat the process. However, in this case, there will be 1 valid frame (the starting frame) to the left and the rest is zero-padded. We do the same thing as we iterate over each index and generate video clips for them. Index 16 will be the first one to have a whole window consisting of valid frames from the video since `start=16-1*32/2=0` and `end=16+1*32/2=32`. 

I hope this makes it more clear. Since we traverse each index, the video clips generated are not exactly the same. There might be overlap of some frames, which is expected but this does not necessarily mean that the features will be exactly the same. Each feature relates to each index or central frame in a clip. eg. feature 0 comes from index 0, feature 1 comes from index 1 and so on.
You can play around with the `in_fps` and `out_fps` config parameters to sparsely sample the feature. If you only need to process the input video at a lower fps like 10 fps, I would recommend setting both in_fps and out_fps to that value.

**Comment by habatua** [comment]
Thank you very much. I can understand the method under your help.

**Comment by tridivb** [comment]
You are welcome.
